### ISSUE TITLE
[Big Feature] Make it possible to create plugins

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/r2-oas#142]
## Summary

Make it possible to create plugins like fluentd.

```
r2oas-plugin-generate <type> <name>
```

e.g.)

`fluent-plugin-sample/lib/fluent/plugin/out_sample.rb`

```rb
module Fluent
  module Plugin
    class SampleOutput < Fluent::Plugin::Output
      Fluent::Plugin.register_output("sample", self)

      def format(tag, time, record)
        [tag, time, record].to_msgpack
      end

      def formatted_to_msgpack_binary?
        true
      end

      def write(chunk)
        chunk.msgpack_each do |tag, time, data|
          p tag
          p time
          p data
        end
      end

    end
  end
end
```

## Reference

- `https://qiita.com/suzuki-navi/items/57ec168267466a343a8a`
- `https://qiita.com/tanan/items/625329234dc2b36a1c58`
-https://github.com/fluent/fluentd/blob/afdd90780a12a0010775743bb24651b271e5b54a/lib/fluent/command/plugin_generator.rb

- https://docs.fluentd.org/deployment/command-line-option#fluent-plugin-generate

```
Usage: fluent-plugin-generate [options] <type> <name>

Generate a project skeleton for creating a Fluentd plugin

Arguments:
        type: input,output,filter,parser,formatter
        name: Your plugin name

Options:
        --[no-]license=NAME          Specify license name (default: Apache-2.0)
```

```
$ fluent-plugin-generate filter hogehoge
License: Apache-2.0
    create Gemfile
    create README.md
    create Rakefile
    create fluent-plugin-onekeyparse.gemspec
    create lib/fluent/plugin/filter_hogehoge.rb
    create test/helper.rb
    create test/plugin/test_filter_hogehoge.rb
Initialized empty Git repository in /xxxx/fluent-plugin-hogehoge/.git/
```

## Memo

- rename

```diff
- plugins/schema/v3/object/hookable_base_object.rb 
+ dynamics/schema/v3/object/hookable_base_object.rb 
```
