### ISSUE TITLE
 Make sure that `http_status does` not generate `204` and `404` component schemas

### ISSUE THREAD

**Issue by yukihirop** [yukihirop/r2-oas#98]
### Summary

Make sure that `http_status does` not generate `204` and `404` component schemas

```
        '204':
          description: api/v1/partner description
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/V1_Partner_P1_204_PUT"
        '404':
          description: api/v1/partner description
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/V1_Partner_P1_404_PUT"
```

### System configuration
**r2-oas version**: 

```
[1] pry(main)> R2OAS::VERSION
=> "0.1.0"
```

**Ruby version**:

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin18]
```
